### ISSUE TITLE
Any chance you can document the process for generating the "keys_chords" data?

### ISSUE THREAD

**Issue by znmeb** [mikldk/pichor#1]
I'm using `pichor` to generate keyboard plots in my package <https://github.com/AlgoCompSynth/eikosany>. Two of my synthesizers have 37-key keyboards, so I want to generate keyboard plots for them instead of the `pichor` default of 24 keys.

I think I figured out how to do it - edit the script `generate_data.R`, change `N` to `22L`, source it and then execute `generate_sysdata()`. Is that right?

**Comment by mikldk** [comment]
@znmeb Thanks for submitting this issue! I have commited a change such that a new function `generate_keys_chords()` is exported. Is that a useful change, or do you need something else/more?

**Comment by znmeb** [comment]
That's fine! Thanks!
